### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by jachermocilla** [ivancheesecake/Bertud#1]
Do you have instructions on how to set this up?I want to try out the code.

Thanks!

**Comment by ivancheesecake** [comment]
Good day, Sir!

Sir, pwede po siguro kami pumunta sa office niyo, mahaba-haba po ang setup
eh. Mag-coconsult din po kami. :)

Some notes po:
1. Windows po ang kailangang OS, malaking dependency po yung LASTools
2. Web application po yung main interface niya, we can try this out in Linux
3. Medyo madami pong python libraries na kailangang i-install

Thanks, Sir!:)

Regards,

**Comment by jachermocilla** [comment]
Sure. Tamang-tama andito Miyah. 10-1 Wed ang allocated time namin sa Phil-lidar

**Comment by ivancheesecake** [comment]
Sir, sige po punta kami diyan. :))

Regards,
